insert into categoria (Nombre) value("Policiaca");
insert into categoria (Nombre) value("Romantica");
insert into categoria (Nombre) value("Aventuras");
insert into categoria (Nombre) value("Comedia");
insert into categoria (Nombre) value("Animacion");
insert into categoria (Nombre) value("Thriller");
insert into abono (Nombre, Abono_id, Categoria_id) values("Basico(Policiaca)",1,1);
insert into abono (Nombre, Abono_id, Categoria_id) values("Basico(Romantica)",2,2);
insert into abono (Nombre, Abono_id, Categoria_id) values("Basico(Comedia)",3,4);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Aventuras,Romantica,Comedia)",4,3);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Aventuras,Romantica,Comedia)",4,2);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Aventuras,Romantica,Comedia)",4,4);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Policiaca,Animacion,Thriller)",5,1);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Policiaca,Animacion,Thriller)",5,5);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Policiaca,Animacion,Thriller)",5,6);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Romantica,Comedia,Animacion)",6,2);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Romantica,Comedia,Animacion)",6,4);
insert into abono (Nombre, Abono_id, Categoria_id) values("Extra(Romantica,Comedia,Animacion)",6,5);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,1);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,2);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,3);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,4);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,5);
insert into abono (Nombre, Abono_id, Categoria_id) values("Premium",7,6);
